"""
Self-contained HTML migration impact report generator.
No external CDN — everything is inlined.
"""
from __future__ import annotations

import datetime
import json
from pathlib import Path
from typing import Optional

from pqc_sandbox.benchmarks.runner import ComparisonResult
from pqc_sandbox.compat.oracle import CompatReport, Severity
from pqc_sandbox.hybrid.simulator import HybridResult
from pqc_sandbox.scoring import MigrationScore

_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>PQC Migration Impact Report — pqc-sandbox</title>
<style>
:root{--bg:#0d1117;--card:#161b22;--border:#30363d;--accent:#58a6ff;--green:#3fb950;--yellow:#d29922;--red:#f85149;--orange:#d18616;--text:#c9d1d9;--dim:#8b949e}
*{box-sizing:border-box;margin:0;padding:0}
body{background:var(--bg);color:var(--text);font-family:'Segoe UI',system-ui,sans-serif;font-size:14px;line-height:1.6;padding:24px}
h1{font-size:22px;font-weight:700;color:#e6edf3;margin-bottom:4px}
h2{font-size:16px;font-weight:600;color:var(--accent);margin:20px 0 10px}
.subtitle{color:var(--dim);font-size:12px;margin-bottom:24px}
.card{background:var(--card);border:1px solid var(--border);border-radius:8px;padding:20px;margin-bottom:20px}
table{width:100%;border-collapse:collapse}
th{text-align:left;color:var(--accent);font-weight:600;border-bottom:1px solid var(--border);padding:8px 12px;font-size:12px;text-transform:uppercase;letter-spacing:.05em}
td{padding:8px 12px;border-bottom:1px solid #21262d;font-size:13px}
tr:last-child td{border-bottom:none}
.up{color:var(--red)}
.down{color:var(--green)}
.neutral{color:var(--dim)}
.badge-go{background:#1a4a2e;color:var(--green);border:1px solid var(--green);padding:3px 10px;border-radius:20px;font-size:12px;font-weight:700}
.badge-caution{background:#3d2f00;color:var(--yellow);border:1px solid var(--yellow);padding:3px 10px;border-radius:20px;font-size:12px;font-weight:700}
.badge-blocked{background:#3d0c12;color:var(--red);border:1px solid var(--red);padding:3px 10px;border-radius:20px;font-size:12px;font-weight:700}
.issue{padding:12px;border-radius:6px;margin-bottom:8px}
.issue-blocked{background:#2d1117;border-left:3px solid var(--red)}
.issue-caution{background:#2d2100;border-left:3px solid var(--yellow)}
.issue-info{background:#121d2f;border-left:3px solid var(--accent)}
.issue-title{font-weight:600;margin-bottom:4px}
.issue-detail{color:var(--dim);font-size:12px}
.mitigation{color:#58a6ff;font-size:11px;margin-top:6px}
.score-bar-wrap{background:#21262d;border-radius:6px;height:14px;margin:8px 0;overflow:hidden}
.score-bar{height:100%;border-radius:6px;transition:width .4s}
.score-easy{background:var(--green)}
.score-moderate{background:var(--yellow)}
.score-hard{background:var(--orange)}
.score-critical{background:var(--red)}
.score-num{font-size:28px;font-weight:800;margin-right:10px}
.meta{color:var(--dim);font-size:11px;margin-top:4px}
.badge-img{margin:10px 0}
.mono{font-family:monospace;background:#21262d;padding:2px 6px;border-radius:4px;font-size:12px}
footer{color:var(--dim);font-size:11px;margin-top:32px;text-align:center}
.grid2{display:grid;grid-template-columns:1fr 1fr;gap:16px}
@media(max-width:640px){.grid2{grid-template-columns:1fr}}
.tag{display:inline-block;background:#21262d;border-radius:12px;padding:2px 8px;font-size:11px;margin-right:4px}
</style>
</head>
<body>

<h1>🔐 PQC Migration Impact Report</h1>
<div class="subtitle">Generated by <strong>pqc-sandbox</strong> &nbsp;·&nbsp; {{timestamp}} &nbsp;·&nbsp; Zero cloud, zero telemetry &nbsp;·&nbsp; All analysis runs locally.</div>

{{verdict_banner}}

{{benchmark_section}}

{{hybrid_section}}

{{compat_section}}

{{score_section}}

{{badge_section}}

<footer>
  Generated by <a href="https://github.com/pqc-sandbox/pqc-sandbox" style="color:var(--accent)">pqc-sandbox</a>
  &nbsp;·&nbsp; Apache 2.0 &nbsp;·&nbsp; NIST PQC algorithms: FIPS 203/204/205
</footer>
</body>
</html>
"""


def _fmt_bytes(n: int) -> str:
    if n >= 1_048_576:
        return f"{n / 1_048_576:.1f} MB"
    if n >= 1_024:
        return f"{n / 1_024:.1f} KB"
    return f"{n} B"


def _delta_td(n: float, unit: str = "", positive_is_bad: bool = True) -> str:
    cls = ""
    prefix = "+" if n >= 0 else ""
    if n > 0:
        cls = "up" if positive_is_bad else "down"
    elif n < 0:
        cls = "down" if positive_is_bad else "up"
    else:
        cls = "neutral"
    if isinstance(n, int) or unit == "":
        return f'<td class="{cls}">{prefix}{n:,.0f}{unit}</td>'
    return f'<td class="{cls}">{prefix}{n:.3f}{unit}</td>'


def _ratio_td(ratio: float) -> str:
    cls = "up" if ratio > 2 else "neutral"
    return f'<td class="{cls}">{ratio:.1f}×</td>'


def _build_benchmark(cmp: ComparisonResult) -> str:
    cl, pq = cmp.classical, cmp.pqc

    def timing_row(label: str, c_ms: float, p_ms: float) -> str:
        ratio = p_ms / c_ms if c_ms > 0 else 0
        return (
            f"<tr><td><strong>{label}</strong></td>"
            f"<td>{c_ms:.3f} ms</td><td>{p_ms:.3f} ms</td>"
            + _delta_td(p_ms - c_ms, " ms")
            + _ratio_td(ratio)
            + "</tr>"
        )

    def size_row(label: str, c_b: int, p_b: int) -> str:
        ratio = p_b / c_b if c_b > 0 else 0
        return (
            f"<tr><td><strong>{label}</strong></td>"
            f"<td>{_fmt_bytes(c_b)}</td><td>{_fmt_bytes(p_b)}</td>"
            + _delta_td(p_b - c_b, " B")
            + _ratio_td(ratio)
            + "</tr>"
        )

    op1 = "Encapsulate" if pq.category == "kem" else "Sign"
    op2 = "Decapsulate" if pq.category == "kem" else "Verify"
    art = "Ciphertext" if pq.category == "kem" else "Signature"

    source_note = "(liboqs)" if pq.oqs_used else "(simulated — install liboqs for real measurements)"

    rows = (
        timing_row("KeyGen", cl.keygen_ms, pq.keygen_ms)
        + timing_row(op1, cl.operation1_ms, pq.operation1_ms)
        + timing_row(op2, cl.operation2_ms, pq.operation2_ms)
        + "<tr><td colspan=5 style='padding:0;border-bottom:1px solid #30363d'></td></tr>"
        + size_row("Public Key", cl.public_key_bytes, pq.public_key_bytes)
        + size_row("Private Key", cl.private_key_bytes, pq.private_key_bytes)
        + size_row(art, cl.artifact_bytes, pq.artifact_bytes)
    )

    return f"""
<div class="card">
  <h2>Side-by-Side Benchmark</h2>
  <p class="meta">{cl.algorithm} (classical) → {pq.algorithm} (PQC) &nbsp; <span class="tag">{source_note}</span></p>
  <table>
    <thead><tr><th>Metric</th><th>Classical</th><th>PQC</th><th>Delta</th><th>Ratio</th></tr></thead>
    <tbody>{rows}</tbody>
  </table>
</div>
"""


def _build_hybrid(h: HybridResult) -> str:
    def row(name: str, kg: float, op1: float, op2: float, art: int, bold: bool = False) -> str:
        b = "style='font-weight:700'" if bold else ""
        return (
            f"<tr {b}><td>{name}</td>"
            f"<td>{kg:.3f} ms</td><td>{op1:.3f} ms</td><td>{op2:.3f} ms</td>"
            f"<td>{_fmt_bytes(art)}</td></tr>"
        )

    rows = (
        row(h.classical_name, h.classical_bench.keygen_ms, h.classical_bench.operation1_ms,
            h.classical_bench.operation2_ms, h.classical_bench.artifact_bytes)
        + row(h.pqc_name, h.pqc_bench.keygen_ms, h.pqc_bench.operation1_ms,
              h.pqc_bench.operation2_ms, h.pqc_bench.artifact_bytes)
        + row("HYBRID TOTAL", h.combined_keygen_ms, h.combined_op1_ms,
              h.combined_op2_ms, h.combined_artifact_bytes, bold=True)
    )

    return f"""
<div class="card">
  <h2>Hybrid Mode: {h.label}</h2>
  <p class="meta">Classical + PQC run in parallel — security degrades gracefully if one is broken.
    Wire overhead vs. classical only: <strong>+{h.wire_overhead_bytes:,} B</strong></p>
  <table>
    <thead><tr><th>Component</th><th>KeyGen</th><th>Op1</th><th>Op2</th><th>Wire artifact</th></tr></thead>
    <tbody>{rows}</tbody>
  </table>
</div>
"""


def _build_compat(cr: CompatReport) -> str:
    if not cr.issues:
        return '<div class="card"><h2>Compatibility</h2><p style="color:var(--green)">✓ No issues detected.</p></div>'

    issue_html = ""
    for issue in cr.issues:
        cls_map = {
            Severity.BLOCKED: "issue-blocked",
            Severity.CAUTION: "issue-caution",
            Severity.INFO:    "issue-info",
            Severity.OK:      "issue-info",
        }
        icon_map = {
            Severity.BLOCKED: "✗",
            Severity.CAUTION: "⚠",
            Severity.INFO:    "ℹ",
            Severity.OK:      "✓",
        }
        mit = f'<div class="mitigation">💡 {issue.mitigation}</div>' if issue.mitigation else ""
        issue_html += f"""
<div class="issue {cls_map[issue.severity]}">
  <div class="issue-title">{icon_map[issue.severity]} [{issue.category.upper()}] {issue.title}</div>
  <div class="issue-detail">{issue.detail}</div>
  {mit}
</div>"""

    return f'<div class="card"><h2>Compatibility Oracle</h2>{issue_html}</div>'


def _build_score(score: MigrationScore) -> str:
    cls_map = {"EASY": "score-easy", "MODERATE": "score-moderate",
               "HARD": "score-hard", "CRITICAL": "score-critical"}
    bar_cls = cls_map.get(score.label, "score-easy")
    bullets = "".join(f"<li>{r}</li>" for r in score.rationale)
    sub = "".join(
        f"<tr><td>{k.title()}</td><td>{v}/{'30' if k=='size' else '25' if k=='performance' else '30' if k=='compatibility' else '15'}</td></tr>"
        for k, v in score.breakdown.items()
    )
    return f"""
<div class="card">
  <h2>Migration Difficulty Score</h2>
  <div style="display:flex;align-items:center">
    <span class="score-num">{score.score}</span>
    <span style="font-size:18px;font-weight:700;color:var(--{'green' if score.label=='EASY' else 'yellow' if score.label=='MODERATE' else 'orange' if score.label=='HARD' else 'red'})">{score.label}</span>
  </div>
  <div class="score-bar-wrap"><div class="score-bar {bar_cls}" style="width:{score.score}%"></div></div>
  <div class="grid2">
    <table><thead><tr><th>Sub-score</th><th>Points</th></tr></thead><tbody>{sub}</tbody></table>
    <ul style="padding-left:16px;color:var(--dim);font-size:12px">{bullets}</ul>
  </div>
</div>
"""


def _build_badge(score: MigrationScore) -> str:
    return f"""
<div class="card">
  <h2>README Badge</h2>
  <p class="meta">Add this to your project README to show your migration readiness:</p>
  <div class="badge-img"><img src="{score.badge_url}" alt="PQC Migration: {score.label}"></div>
  <pre class="mono" style="white-space:pre-wrap;padding:12px;margin-top:8px">{score.badge_markdown}</pre>
</div>
"""


def generate_html(
    comparison: Optional[ComparisonResult] = None,
    compat: Optional[CompatReport] = None,
    hybrid: Optional[HybridResult] = None,
    score: Optional[MigrationScore] = None,
    output_path: Optional[Path] = None,
) -> str:
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    verdict = "GO"
    if compat:
        verdict = compat.verdict
    verdict_cls = {"GO": "badge-go", "CAUTION": "badge-caution", "BLOCKED": "badge-blocked"}
    verdict_banner = f'<div class="card" style="text-align:center;padding:14px"><span class="{verdict_cls.get(verdict,"")}">VERDICT: {verdict}</span></div>'

    html = _TEMPLATE.replace("{{timestamp}}", now)
    html = html.replace("{{verdict_banner}}", verdict_banner)
    html = html.replace("{{benchmark_section}}", _build_benchmark(comparison) if comparison else "")
    html = html.replace("{{hybrid_section}}", _build_hybrid(hybrid) if hybrid else "")
    html = html.replace("{{compat_section}}", _build_compat(compat) if compat else "")
    html = html.replace("{{score_section}}", _build_score(score) if score else "")
    html = html.replace("{{badge_section}}", _build_badge(score) if score else "")

    if output_path:
        Path(output_path).write_text(html, encoding="utf-8")

    return html
